---
- name: create kubernetes config directories
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/kubernetes"
    - "/srv/kubernetes"
    - "{{ kube_manifest_dir }}"
    - "{{ kube_podmaster_dir }}"
    - "{{ kube_cert_dir }}"
    - "{{ kube_users_dir }}"
  tags:
    - kubernetes

- name: pull hyperkube docker image
  sudo: yes
  command: "docker pull {{ kube_hyperkube_image }}:{{ kube_version }}"
  register: docker_pull_result
  changed_when: docker_pull_result.stdout.find('newer') > -1
  tags:
    - kubernetes

- include: secrets.yml
  tags:
    - secrets
    - kubernetes
