---
- name: install traefik
  sudo: yes
  get_url:
    url: https://github.com/containous/traefik/releases/download/v1.0.0-rc2/traefik_linux-amd64
    dest: /usr/bin/traefik-internal
    mode: 0755
  tags:
    - traefik-internal
    - bootstrap

- name: Grant permission to bind to priviledged port
  sudo: yes
  shell: "setcap 'cap_net_bind_service=+ep' /usr/bin/traefik-internal"
  tags:
    - traefik-internal
    - bootstrap

- name: create traefik-internal unit file
  sudo: yes
  shell: "cp /etc/systemd/system/traefik.service /etc/systemd/system/traefik-internal.service"
  tags:
    - traefik-internal
    - bootstrap

- name: configure traefik-internal unit file logging
  sudo: yes
  replace:
    dest: /etc/systemd/system/traefik-internal.service
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '/etc/traefik/',     replace: '/etc/traefik-internal/'     }
    - { regexp: '/var/log/traefik/', replace: '/var/log/traefik-internal/' }
    - { regexp: '/usr/bin/traefik ', replace: '/usr/bin/traefik-internal ' } # Note space after binary name is important for idempotents
    - { regexp: '/usr/bin/traefik-internal -c ', replace: '/usr/bin/traefik-internal -c' } # Remove space after -c argument if its there...
  tags:
    - traefik-internal
    - bootstrap

- name: configure traefik-internal to ignore consul http certificate validation
  sudo: yes
  lineinfile:
    dest: /etc/systemd/system/traefik-internal.service
    insertafter: '^\[Service\]'
    line: 'Environment=CONSUL_HTTP_SSL_VERIFY=false'
    state: present
  tags:
    - traefik-internal
    - bootstrap

- name: create logging directory for traefik-internal
  sudo: yes
  file:
    dest: /var/log/traefik-internal
    state: directory
    owner: traefik
    group: traefik
    mode: 0775
  tags:
    - traefik-internal
    - bootstrap

- name: create directory for local traefik service override
  sudo: yes
  file:
    dest: /etc/systemd/system/traefik-internal.service.d
    state: directory
    mode: 0755
  tags:
    - traefik-internal
    - bootstrap

- name: create configuration directory for traefik-internal
  sudo: yes
  file:
    dest: /etc/traefik-internal
    state: directory
    mode: 0755
  tags:
    - traefik-internal
    - bootstrap

- name: configure traefik
  sudo: yes
  template:
    src: traefik.toml.j2
    dest: /etc/traefik-internal/traefik.toml
    owner: traefik
    group: traefik
    mode: 0644
    backup: yes
  notify:
    - reload systemd
    - restart traefik-internal
  tags:
    - traefik-internal

- name: generate traefik consul service
  sudo: yes
  copy:
    src: 'traefik-consul.json'
    dest: '/etc/consul/traefik-internal.json'
  notify:
    - reload consul
  tags:
    - traefik-internal
