---
- include: secrets.yml
  tags:
    - secrets
    - kubernetes

- name: install kubernetes binaries
  sudo: yes
  yum:
    name: "{{ kubernetes_package }}"
    state: present
  tags:
    - node
    - kubernetes

- name: generate kubelet systemd unit
  sudo: yes
  template:
    src: kubelet.service.j2
    dest: /usr/lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - node
    - kubernetes

- name: generate kubelet kubeconfig
  sudo: yes
  template:
    src: node.kubeconfig.j2
    dest: "/etc/kubernetes/node.kubeconfig"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - node
    - kubernetes

- name: enable and start kubelet service
  sudo: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - node
    - kubernetes

- name: generate kubernetes manifests
  sudo: yes
  template:
    src: "{{ item }}.yml"
    dest: "{{ kube_manifest_dir }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-proxy
  tags:
    - node
    - kubernetes

- name: generate consul config for NodePort services
  sudo: yes
  template:
    src: nodeport.json.j2
    dest: /etc/consul/nodeport.json
  notify:
    - reload consul
  tags:
    - node
    - kubernetes

- name: create fluentd pod
  sudo: yes
  copy:
    src: fluentd-es.yaml
    dest: "{{ kube_manifest_dir }}/fluentd-es.yaml"
  when: enable_logging
  tags:
    - addons
    - logging
    - kubernetes
